executor: KubernetesExecutor
airflowVersion: "3.2.2"

defaultAirflowRepository: my-airflow
defaultAirflowTag: "3.2.2-spark"

images:
  airflow:
    repository: my-airflow
    tag: "3.2.2-spark"
    pullPolicy: IfNotPresent

postgresql:
  enabled: true

dags:
  persistence:
    enabled: false
  gitSync:
    enabled: false

scheduler:
  serviceAccount:
    create: false
    name: airflow-sa

workers:
  kubernetes:
    serviceAccount:
      create: false
      name: airflow-sa

logs:
  persistence:
    enabled: false

config:
  core:
    load_examples: "False"
  kubernetes_executor:
    delete_worker_pods: "True"

env:
  - name: AIRFLOW_CONN_SPARK_K8S
    value: >-
      {"conn_type":"spark","host":"k8s://https://kubernetes.default.svc","extra":{"deploy-mode":"cluster","namespace":"airflow","spark-binary":"spark-submit"}}

statsd:
  enabled: false
